CREATE TABLE Client (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    contact_form VARCHAR(255)
);

INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 1',  'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 2',  'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 3',  'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 4',  'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 5',  'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 6',  'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 7',  'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 8',  'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 9',  'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 10', 'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 11', 'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 12', 'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 13', 'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 14', 'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 15', 'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 16', 'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 17', 'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 18', 'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 19', 'prueba7410258@gmail.com');
INSERT INTO CLIENT (NAME, CONTACT_FORM) VALUES ('Client 20', 'prueba7410258@gmail.com');
